import {
  faShieldAlt,
  faCrown,
  faStopwatch,
  faHandshake,
  faAward,
  faStar,
  faUsers,
  faClock,
  faThumbsUp,
} from "@fortawesome/free-solid-svg-icons";

import type { ClientConfig } from "../types/Config";

const clientBeakomConfig: ClientConfig = {
  name: "Beakom Enterprise",
  logo: "Beakom/beakom-logo.png",
  primaryColor: "#c30606",
  primaryColorLight: "#a01a1575",
  secondaryColor: "#000000ff",
  tagline: "Your Trusted Hardware Supplier!",
  fontFamily: "Gill Sans, Gill Sans MT, Calibri, Trebuchet MS, sans-serif",
  currencySymbol: "₵",
  // Project template config starts here
  header: {
    title: "Our Projects",
    subtitle: "Explore our portfolio of completed work.",
  },
  cta: {
    title: "Have a specific hardware fastener in mind?",
    subtitle:
      "We'd love to hear about your needs. Contact us today for more information.",
    buttonText: "Contact Us",
    link: "/contact", // when the contact page is converted should be added here.
  },

  features: [
    {
      icon: faShieldAlt,
      title: "Quality Guaranteed",
      description: "Premium materials and tools for every project.",
    },
    {
      icon: faCrown,
      title: "Luxury Finish",
      description: "Achieve a high-end look with our premium hardware.",
    },
    {
      icon: faStopwatch,
      title: "Timely Delivery",
      description: "Meeting deadlines with precision and efficiency",
    },
    {
      icon: faHandshake,
      title: "Reliability",
      description:
        "Count on us for consistent quality and dependable products.",
    },
    {
      icon: faAward,
      title: "Trust",
      description: "Building lasting relationships with our clients.",
    },
    {
      icon: faStar,
      title: "Customer Satisfaction",
      description: "Your satisfaction is our top priority.",
    },
  ],
  about: {
    title: "About Us",
    subtitle: "Who we are and what we do.",
    description:
      "Beakom Enterprises is a leading provider of high-quality hardware fasteners.",
    image: "/images/about-team.jpg",

    // Story section fields
    // Story section fields
    mainImage: "Beakom/beakom-logo.png", // or your story image path
    mainImageAlt: "Beakom Team",
    storyTitle: "Our Story",
    story1:
      "Founded in 2016 by Mrs Jasmine, Beakom has become a leader in the hardware fastener industry in Ghana.",
    story2:
      "With a focus on quality and customer satisfaction, we have built a strong reputation for delivering reliable products and services.",
    story3:
      "Our mission is to provide the best hardware solutions to our clients and to be a trusted partner in their success.",

    // Values section
    values: [
      {
        icon: faShieldAlt,
        title: "Quality",
        description:
          "We never compromise on quality, using only the finest materials and proven construction methods.",
      },
      {
        icon: faUsers,
        title: "Trust",
        description:
          "Building lasting relationships with our clients through transparency and reliability.",
      },
      {
        icon: faClock,
        title: "Timeliness",
        description:
          "We respect deadlines and deliver projects on schedule without compromising quality.",
      },
      {
        icon: faThumbsUp,
        title: "Customer Satisfaction",
        description:
          "Your satisfaction is our ultimate goal, and we go above and beyond to achieve it.",
      },
    ],

    // Founder section fields
    founderImage: "/images/founder.jpg", // or your founder image path
    founderTitle: "Meet The Founder",
    founderName: "Mrs Jasmine",
    founderRole: "Founder & CEO",
    founderBio1:
      "With over 15 years of experience in the construction industry, Mrs Jasmine has established herself as a visionary leader providing innovative solutions.",
    founderBio2:
      "In 2016, driven by her passion for excellence, Mrs Jasmine founded Beakom. Under her leadership, the company has grown from handling small residential projects to managing complex commercial developments.",
    founderBio3:
      "Mrs Jasmine's hands-on approach and dedication to client satisfaction have been instrumental in building Beakom's reputation.",
    // Optional SEO fields
    // seoTitle: "About Beakom - Expert Construction Company",
    // seoDescription: "Learn about Beakom, a trusted construction company with 9+ years experience in house extensions, renovations & new builds.",
    // seoKeywords: "about Beakom, construction company, experienced builders, construction history",
    // seoUrl: "https://yourdomain.com/about"
  },
  phoneOffice: "053 135 6424",
  phoneMobile: "(+233) 53 135 6424",
  email: "Beakomenterprisegh@gmail.com",
  address: "Hanson lane, Arena station, Accra",
  openHours1: "Monday - Friday: 8:00 AM - 4:30 PM",
  openHours2: "Saturday: Closed",
  openHours3: "Sunday: Closed",
  location:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2478.8832781725673!2d-0.22423112337504625!3d51.58870257183188!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487610cf8629b6f3%3A0x4802d5cd36a9a63!2s137%20Brent%20St%2C%20London%20NW4%204DJ!5e0!3m2!1sen!2suk!4v1747849113481!5m2!1sen!2suk",
  hero: {
    title: "Building Your Vision with Precision",
    subtitle:
      "Supplying you with all the hardware fasteners you need for your projects.",

    backgroundImage: "Beakom/beakom-background.png",
  },
  featuredItems: {
    title: "Best Sellers",
    subtitle: "Top-rated hardware at unbeatable prices",
    products: [
      {
        id: 1,
        name: "Hex Bolt 16mm (Galvanized)",
        image:
          "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822057/HDG_oqczgd.webp",
        price: 129.99,
        originalPrice: 179.99,
        stock: 42,
        priceRange: {
          min: 89.99,
          max: 229.99,
        },
        rating: 4.8,
      },
      {
        id: 2,
        name: "Toggle Wing (Galvanized)",
        image:
          "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822055/toggle_wing_galvanized_nyysj7.webp",
        price: 89.5,
        originalPrice: 119.99,
        stock: 15,
        priceRange: {
          min: 59.99,
          max: 159.99,
        },
        rating: 4.5,
      },
      {
        id: 3,
        name: "Machine Screw (142pc)",
        image:
          "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822062/galvanized_o2mjeo.webp",
        price: 249.99,
        originalPrice: 349.99,
        stock: 8,
        priceRange: {
          min: 199.99,
          max: 499.99,
        },
        rating: 4.9,
      },
      {
        id: 4,
        name: "Lock Nut (Galvanized)",
        image:
          "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822065/lock_nut_rx4ge0.webp",
        price: 24.99,
        originalPrice: 34.99,
        stock: 0, // Out of stock
        priceRange: {
          min: 19.99,
          max: 49.99,
        },
        rating: 4.3,
      },
      {
        id: 5,
        name: "Tabular Rivet (Galvanized)",
        image:
          "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754829177/tubular_rivet_ocfo2s.webp",
        price: 59.99,
        originalPrice: 79.99,
        stock: 23,
        priceRange: {
          min: 39.99,
          max: 129.99,
        },
        rating: 4.7,
      },
    ],
  },
  filterGroup: [
    {
      title: "Hardware Tool",
      options: [
        { name: "Bolts", count: 113, selected: false },
        { name: "Socket Screws", count: 140, selected: false },
        { name: "Anchors & Expansion Fixings", count: 348, selected: false },
        { name: "General Screws", count: 150, selected: false },
        { name: "Nuts", count: 200, selected: false },
        { name: "Washers", count: 100, selected: false },
        { name: "Retaining Rings & Keys", count: 50, selected: false },
        { name: "Pins & Rivets", count: 75, selected: false },
        { name: "Anchor Plugs", count: 30, selected: false },
        { name: "Other Materials", count: 30, selected: false },
      ],
      type: "checkbox",
    },
    {
      title: "Material",
      options: [
        { name: "Mild Steel", count: 140, selected: false },
        { name: "Stainless Steel", count: 113, selected: false },
        { name: "Brass", count: 80, selected: false },
        { name: "Copper", count: 50, selected: false },
        { name: "Rubber", count: 30, selected: false },
        { name: "Nylon", count: 25, selected: false },
        { name: "Cast Iron", count: 13, selected: false },
        { name: "Malleable Iron", count: 348, selected: false },
      ],
      type: "checkbox",
    },
    {
      title: "Material Finish",
      options: [
        { name: "Raw Steel", count: 780, selected: false },
        { name: "Galvanized", count: 466, selected: false },
        { name: "Zinc", count: 300, selected: false },
        { name: "HDG", count: 200, selected: false },
        { name: "Stainless", count: 150, selected: false },
        { name: "Coated", count: 100, selected: false },
      ],
      type: "checkbox",
    },
  ],
  products: [
    // BOLTS
    {
      id: "1",
      code: "HB16",
      name: "Hex Bolt 16mm (Stainless Steel)",
      type: "Bolts",
      price: 1.2,
      vatPrice: 1.46,
      stock: 100,
      description: "Stainless steel hex bolt with full thread",
      material: "Stainless Steel",
      finish: "Stainless",
      size: "16mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822058/zinc_qkkiq0.jpg",
      ],
      specifications: [
        { key: "Type", value: "Hex Bolt" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "16mm" },
        { key: "Length", value: "100mm" },
      ],
    },
    {
      id: "2",
      code: "SFB12",
      name: "Hex Bolt, Stainless Steel",
      type: "Bolts",
      price: 0.8,
      vatPrice: 0.96,
      stock: 250,
      description: "Stainless steel hex bolt with full thread",
      material: "Mild Steel",
      finish: "Galvanized",
      size: "12mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822058/stainless_steel_d14qmy.jpg",
      ],
      specifications: [
        { key: "Type", value: "Socket Button Flange Screw" },
        { key: "Material", value: "Mild Steel" },
        { key: "Diameter", value: "12mm" },
        { key: "Length", value: "50mm" },
      ],
    },
    {
      id: "3",
      code: "WAG8",
      name: "Hex Bolt, Galvanized",
      type: "Bolts",
      price: 0.95,
      vatPrice: 1.14,
      stock: 80,
      description: "Galvanized hex bolt with full thread",
      material: "Mild Steel",
      finish: "Galvanized",
      size: "8mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822057/HDG_oqczgd.webp",
      ],
      specifications: [
        { key: "Type", value: "Bolts" },
        { key: "Material", value: "Mild Steel" },
        { key: "Diameter", value: "8mm" },
        { key: "Length", value: "80mm" },
      ],
    },
    {
      id: "4",
      code: "HN10",
      name: "Hex Bolt 10mm (Brass)",
      type: "Bolts",
      price: 0.25,
      vatPrice: 0.3,
      stock: 500,
      description: "Brass hex bolt with standard thread",
      material: "Brass",
      finish: "Coated",
      size: "10mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822057/brass_fftnix.jpg",
      ],
      specifications: [
        { key: "Type", value: "Hex Bolt" },
        { key: "Material", value: "Brass" },
        { key: "Size", value: "10mm" },
        { key: "Thread", value: "Standard" },
      ],
    },
    {
      id: "5",
      code: "FW16",
      name: "Carriage Bolt 16mm (Zinc)",
      type: "Bolts",
      price: 0.1,
      vatPrice: 0.12,
      stock: 1000,
      description: "Zinc carriage bolt",
      material: "Zinc",
      finish: "Stainless",
      size: "16mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822056/zinc_mpzy4i.webp",
      ],
      specifications: [
        { key: "Type", value: "Carriage Bolt" },
        { key: "Material", value: "Zinc" },
        { key: "Inner Diameter", value: "16mm" },
        { key: "Outer Diameter", value: "30mm" },
      ],
    },
    {
      id: "6",
      code: "EB10",
      name: "Carriage Bolt 10mm (Galvanized)",
      type: "Bolts",
      price: 1.2,
      vatPrice: 1.44,
      stock: 150,
      description: "Galvanized carriage bolt for lifting applications",
      material: "Mild Steel",
      finish: "Galvanized",
      size: "10mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822055/galvanized_wct96v.jpg",
      ],
      specifications: [
        { key: "Type", value: "Carriage Bolt" },
        { key: "Material", value: "Mild Steel" },
        { key: "Diameter", value: "10mm" },
        { key: "Length", value: "100mm" },
      ],
    },
    {
      id: "7",
      code: "TR12",
      name: "Hanger Bolt 12mm (HDG)",
      type: "Bolts",
      price: 2.5,
      vatPrice: 3.0,
      stock: 75,
      description: "Hot-dip galvanized hanger bolt",
      material: "Mild Steel",
      finish: "HDG",
      size: "12mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822057/galvanized_j3y0ks.jpg",
      ],
      specifications: [
        { key: "Type", value: "Hanger Bolt" },
        { key: "Material", value: "Mild Steel" },
        { key: "Diameter", value: "12mm" },
        { key: "Length", value: "1m" },
      ],
    },
    {
      id: "8",
      code: "SW8",
      name: "Hanger Bolt (Brass)",
      type: "Bolts",
      price: 0.15,
      vatPrice: 0.18,
      stock: 800,
      description: "Brass hanger bolt with sharp point",
      material: "Brass",
      finish: "Coated",
      size: "8mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822057/brass_miugee.webp",
      ],
      specifications: [
        { key: "Type", value: "Hanger Bolt" },
        { key: "Material", value: "Brass" },
        { key: "Diameter", value: "8mm" },
        { key: "Length", value: "50mm" },
      ],
    },
    {
      id: "9",
      code: "JB16",
      name: "J Bolt 16mm (HDG)",
      type: "Bolts",
      price: 2.8,
      vatPrice: 3.36,
      stock: 60,
      description: "HDG J-bolt for pipe clamping",
      material: "Mild Steel",
      finish: "HDG",
      size: "16mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822059/HDG_eclies.jpg",
      ],
      specifications: [
        { key: "Type", value: "J Bolt" },
        { key: "Material", value: "Mild Steel" },
        { key: "Diameter", value: "16mm" },
        { key: "Inside Width", value: "50mm" },
      ],
    },
    {
      id: "10",
      code: "JB10",
      name: "J Bolt 10mm (Galvanized)",
      type: "Bolts",
      price: 0.4,
      vatPrice: 0.48,
      stock: 300,
      description: "Galvanized J-bolt for pipe clamping",
      material: "Mild Steel",
      finish: "Galvanized",
      size: "10mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822058/galvanized_zqmszv.webp",
      ],
      specifications: [
        { key: "Type", value: "J Bolt" },
        { key: "Material", value: "Mild Steel" },
        { key: "Size", value: "10mm" },
        { key: "Feature", value: "Nylon Insert" },
      ],
    },
    {
      id: "11",
      code: "DIA10",
      name: "Stud Bolt 10mm (Stainless Steel)",
      type: "Bolts",
      price: 1.2,
      vatPrice: 1.44,
      stock: 120,
      description: "Stud bolt for wood and metal",
      material: "Mild Steel",
      finish: "Stainless Steel",
      size: "10mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822059/stainless_steel_gi4vc1.png",
      ],
      specifications: [
        { key: "Type", value: "Stud Bolt" },
        { key: "Material", value: "Mild Steel" },
        { key: "Diameter", value: "10mm" },
        { key: "Embedment Depth", value: "40mm" },
      ],
    },
    {
      id: "12",
      code: "DIA16",
      name: "Threaded rod (HDG)",
      type: "Bolts",
      price: 0.8,
      vatPrice: 0.96,
      stock: 200,
      description: "Mild steel threaded rod for wood and metal",
      material: "Mild Steel",
      finish: "Galvanized",
      size: "16mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822060/HDG_h5ybj0.webp",
      ],
      specifications: [
        { key: "Type", value: "Threaded Rod" },
        { key: "Material", value: "Mild Steel" },
        { key: "Diameter", value: "16mm" },
        { key: "Embedment Depth", value: "60mm" },
      ],
    },
    {
      id: "13",
      code: "DIA20",
      name: "Threaded rod (Galvanized)",
      type: "Bolts",
      price: 1.0,
      vatPrice: 1.2,
      stock: 150,
      description: "Mild steel threaded rod for concrete",
      material: "Mild Steel",
      finish: "Galvanized",
      size: "20mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822060/galvanized_f5fqux.webp",
      ],
      specifications: [
        { key: "Type", value: "Threaded Rod" },
        { key: "Material", value: "Mild Steel" },
        { key: "Diameter", value: "20mm" },
        { key: "Embedment Depth", value: "80mm" },
      ],
    },
    {
      id: "14",
      code: "DIA25",
      name: "U Bolt (HDG)",
      type: "Bolts",
      price: 2.5,
      vatPrice: 3.0,
      stock: 80,
      description: "HDG U-bolt for pipe clamping",
      material: "Mild Steel",
      finish: "Coated",
      size: "25mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822060/HDG_rb0ozl.jpg",
      ],
      specifications: [
        { key: "Type", value: "U Bolt" },
        { key: "Material", value: "Mild Steel" },
        { key: "Diameter", value: "25mm" },
        { key: "Embedment Depth", value: "100mm" },
      ],
    },
    {
      id: "15",
      code: "DIA30",
      name: "U Bolt (Galvanized)",
      type: "Bolts",
      price: 1.5,
      vatPrice: 1.8,
      stock: 100,
      description: "Mild steel U-bolt for pipe clamping",
      material: "Mild Steel",
      finish: "Galvanized",
      size: "30mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822060/galvanized_vqsacp.jpg",
      ],
      specifications: [
        { key: "Type", value: "Threaded Rod" },
        { key: "Material", value: "Mild Steel" },
        { key: "Diameter", value: "30mm" },
        { key: "Embedment Depth", value: "120mm" },
      ],
    },
    // ANCHORS & EXPANSION FIXINGS
    {
      id: "16",
      code: "DIA40",
      name: "Toggle Wing (Galvanized)",
      type: "Anchors & Expansion Fixings",
      price: 2.0,
      vatPrice: 2.4,
      stock: 90,
      description: "Stainless steel toggle wing for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "40mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822055/toggle_wing_galvanized_nyysj7.webp",
      ],
      specifications: [
        { key: "Type", value: "Anchors & Expansion Fixings" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "40mm" },
        { key: "Embedment Depth", value: "140mm" },
      ],
    },
    {
      id: "17",
      code: "DIA50",
      name: "Wedge anchor (Galvanized)",
      type: "Anchors & Expansion Fixings",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Mild steel wedge anchor for wood and metal",
      material: "Mild Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822055/stainless_steel_q8u3tz.webp",
      ],
      specifications: [
        { key: "Type", value: "Anchors & Expansion Fixings" },
        { key: "Material", value: "Mild Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "18",
      code: "DIA50",
      name: "Sleeve anchor (Galvanized)",
      type: "Anchors & Expansion Fixings",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Mild steel sleeve anchor for concrete",
      material: "Mild Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822055/sleeve_anchor_galvanized_ic6ncu.webp",
      ],
      specifications: [
        { key: "Type", value: "Anchors & Expansion Fixings" },
        { key: "Material", value: "Mild Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "19",
      code: "DIA50",
      name: "Drop-in anchor (Galvanized)",
      type: "Anchors & Expansion Fixings",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Mild steel drop-in anchor for concrete",
      material: "Mild Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822054/drop-in_anchor_galvanized_qk8d43.jpg",
      ],
      specifications: [
        { key: "Type", value: "Anchors & Expansion Fixings" },
        { key: "Material", value: "Mild Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "19",
      code: "DIA50",
      name: "Hollow wall anchor (Galvanized)",
      type: "Anchors & Expansion Fixings",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Stainless steel hollow wall anchor for wood and metal",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822054/hollow_wall_anchor_galvanized_r7k10u.avif",
      ],
      specifications: [
        { key: "Type", value: "Anchors & Expansion Fixings" },
        { key: "Material", value: "Mild Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    // GENERAL SCREWS
    {
      id: "20",
      code: "DIA50",
      name: "Machine Screw (Galvanized)",
      type: "General Screws",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Galvanized machine screw for concrete",
      material: "Galvanized Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822062/galvanized_nmgq60.webp",
      ],
      specifications: [
        { key: "Type", value: "General Screws" },
        { key: "Material", value: "Galvanized Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "21",
      code: "DIA50",
      name: "Mating Screw (Galvanized)",
      type: "General Screws",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Galvanized mating screw for concrete",
      material: "Galvanized Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822062/galvanized_o2mjeo.webp",
      ],
      specifications: [
        { key: "Type", value: "General Screws" },
        { key: "Material", value: "Galvanized Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "22",
      code: "DIA50",
      name: "Wood Screw (Stainless Steel)",
      type: "General Screws",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Stainless steel wood screw for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822064/wood_screw_abkowq.webp",
      ],
      specifications: [
        { key: "Type", value: "General Screws" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "23",
      code: "DIA50",
      name: "Brass Screw (Brass Steel)",
      type: "General Screws",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Brass screw for wood and metal",
      material: "Brass Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822061/brass_screw_e5aobb.jpg",
      ],
      specifications: [
        { key: "Type", value: "General Screws" },
        { key: "Material", value: "Brass Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "24",
      code: "DIA50",
      name: "Copper Screw (Copper Steel)",
      type: "General Screws",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Copper screw for concrete",
      material: "Copper Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822061/copper_screw_ww5s2y.jpg",
      ],
      specifications: [
        { key: "Type", value: "General Screws" },
        { key: "Material", value: "Copper Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "25",
      code: "DIA50",
      name: "Dry Wall Screw (Stainless Steel)",
      type: "General Screws",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Dry wall screw for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822061/drywall_screw_cbny9c.webp",
      ],
      specifications: [
        { key: "Type", value: "General Screws" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "26",
      code: "DIA50",
      name: "Roofing Screw (Brass Steel)",
      type: "General Screws",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Brass screw for wood and metal",
      material: "Brass Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822063/roofing_screw_xkdwoc.jpg",
      ],
      specifications: [
        { key: "Type", value: "General Screws" },
        { key: "Material", value: "Brass Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "27",
      code: "DIA50",
      name: "Thumb Screw (Stainless Steel)",
      type: "General Screws",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Thumb screw for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822064/thumb_screw_itjt5w.jpg",
      ],
      specifications: [
        { key: "Type", value: "General Screws" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "28",
      code: "DIA50",
      name: "Thread cutting Screw (Stainless Steel)",
      type: "General Screws",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Thread cutting screw for wood and metal",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822063/thread_cutting_screw_k18rpr.jpg",
      ],
      specifications: [
        { key: "Type", value: "General Screws" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    // NUTS
    {
      id: "30",
      code: "DIA50",
      name: "Lock Nut (Stainless Steel)",
      type: "Nuts",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Lock nut for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822065/lock_nut_rx4ge0.webp",
      ],
      specifications: [
        { key: "Type", value: "Nuts" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "31",
      code: "DIA50",
      name: "Cap Nut (Stainless Steel)",
      type: "Nuts",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Cap nut for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822064/cap_nut_czag11.jpg",
      ],
      specifications: [
        { key: "Type", value: "Nuts" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },

    {
      id: "32",
      code: "DIA50",
      name: "Hex Nut (Stainless Steel)",
      type: "Nuts",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Hex nut for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822064/hex_nut_wdqgp0.jpg",
      ],
      specifications: [
        { key: "Type", value: "Nuts" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "33",
      code: "DIA50",
      name: "Jam Nut (Stainless Steel)",
      type: "Nuts",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Jam nut for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822065/jam_nut_b9xagp.avif",
      ],
      specifications: [
        { key: "Type", value: "Nuts" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "34",
      code: "DIA50",
      name: "Long Nut (Stainless Steel)",
      type: "Nuts",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Long nut for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822065/long_nut_yqaold.jpg",
      ],
      specifications: [
        { key: "Type", value: "Nuts" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "35",
      code: "DIA50",
      name: "Tea Nut (Stainless Steel)",
      type: "Nuts",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Tea nut for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822066/tee_nut_lwoxro.jpg",
      ],
      specifications: [
        { key: "Type", value: "Nuts" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "36",
      code: "DIA50",
      name: "Wood Nut (Stainless Steel)",
      type: "Nuts",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Wood nut for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822066/wood_nut_ssjx7k.jpg",
      ],
      specifications: [
        { key: "Type", value: "Nuts" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "37",
      code: "DIA50",
      name: "Castle Nut (Stainless Steel)",
      type: "Nuts",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Castle nut for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754824063/castle_nut_pwfjvw.jpg",
      ],
      specifications: [
        { key: "Type", value: "Nuts" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "38",
      code: "DIA50",
      name: "Flange Nut (Stainless Steel)",
      type: "Nuts",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Flange nut for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754824069/flange_nut_dfivru.jpg",
      ],
      specifications: [
        { key: "Type", value: "Nuts" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "39",
      code: "DIA50",
      name: "Cross Barrel Nut (Stainless Steel)",
      type: "Nuts",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Cross barrel nut for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754824066/cross_barrel_nut_ufs2zz.jpg",
      ],
      specifications: [
        { key: "Type", value: "Nuts" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "40",
      code: "DIA50",
      name: "Rubber Nut (Stainless Steel)",
      type: "Nuts",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Rubber nut for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754824075/rubber_nut_hog5c7.jpg",
      ],
      specifications: [
        { key: "Type", value: "Nuts" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    // PINS RIVETS
    {
      id: "41",
      code: "DIA50",
      name: "Tabular Rivet (Stainless Steel)",
      type: "Pins & Rivets",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Tabular rivet for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754829177/tubular_rivet_ocfo2s.webp",
      ],
      specifications: [
        { key: "Type", value: "Pins & Rivets" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "42",
      code: "DIA50",
      name: "Clevis Pins (Stainless Steel)",
      type: "Pins & Rivets",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Clevis pins for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754829162/clevis_pin_fmyocz.webp",
      ],
      specifications: [
        { key: "Type", value: "Pins & Rivets" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "43",
      code: "DIA50",
      name: "Cotter Split Pins (Stainless Steel)",
      type: "Pins & Rivets",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Cotter split pins for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754829165/cotter_split_pin_rl4zv0.webp",
      ],
      specifications: [
        { key: "Type", value: "Pins & Rivets" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "44",
      code: "DIA50",
      name: "Hollow Dowel (Stainless Steel)",
      type: "Pins & Rivets",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Hollow dowel for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754829168/hollow_dowel_pin_jcvkfx.webp",
      ],
      specifications: [
        { key: "Type", value: "Pins & Rivets" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "45",
      code: "DIA50",
      name: "Blind Rivet (Stainless Steel)",
      type: "Pins & Rivets",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Blind rivets for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754829159/blind_rivet_xoewko.webp",
      ],
      specifications: [
        { key: "Type", value: "Pins & Rivets" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "46",
      code: "DIA50",
      name: "Inserts (Stainless Steel)",
      type: "Pins & Rivets",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Inserts for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754829171/inserts_tgeljn.webp",
      ],
      specifications: [
        { key: "Type", value: "Pins & Rivets" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    // RETAINING RINGS AND Keys
    {
      id: "47",
      code: "DIA50",
      name: "Tapered Retaining Rings (Stainless Steel)",
      type: "Retaining Rings & Keys",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Tapered retaining rings for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754827963/tapered_retaining_rings_sex4ja.png",
      ],
      specifications: [
        { key: "Type", value: "Retaining Rings & Keys" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "48",
      code: "DIA50",
      name: "Push On Rings (Stainless Steel)",
      type: "Retaining Rings & Keys",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Push on rings for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754827954/push-on_ring_unf6li.jpg",
      ],
      specifications: [
        { key: "Type", value: "Retaining Rings & Keys" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "49",
      code: "DIA50",
      name: "Snap Rings (Stainless Steel)",
      type: "Retaining Rings & Keys",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Snap rings for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754827957/snap_rings_m8hwpx.jpg",
      ],
      specifications: [
        { key: "Type", value: "Retaining Rings & Keys" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "50",
      code: "DIA50",
      name: "Feathered Shaft Key (Stainless Steel)",
      type: "Retaining Rings & Keys",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Feathered shaft keys for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754827945/feahter_shaft_key_ys0oop.webp",
      ],
      specifications: [
        { key: "Type", value: "Retaining Rings & Keys" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "51",
      code: "DIA50",
      name: "Dowel Shaft Key (Stainless Steel)",
      type: "Retaining Rings & Keys",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Dowel shaft keys for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754827940/dowel_shaft_key_qjspbv.jpg",
      ],
      specifications: [
        { key: "Type", value: "Retaining Rings & Keys" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "51",
      code: "DIA50",
      name: "Grip Ring (Stainless Steel)",
      type: "Retaining Rings & Keys",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Grip rings for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754827948/grip_ring_xayi1w.avif",
      ],
      specifications: [
        { key: "Type", value: "Retaining Rings & Keys" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    // Socket Screws
    {
      id: "52",
      code: "DIA50",
      name: "Hex Socket Head (Stainless Steel)",
      type: "Socket Screws",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Socket screws for concrete",
      material: "Stainless Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822067/stainless_steel_yg3wh6.jpg",
      ],
      specifications: [
        { key: "Type", value: "Socket Screws" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "53",
      code: "DIA50",
      name: "Hex Socket Head Screw (Mild Steel)",
      type: "Socket Screws",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Hex socket head screws for concrete",
      material: "Mild Steel",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822067/mild_steel_hybl7g.jpg",
      ],
      specifications: [
        { key: "Type", value: "Socket Screws" },
        { key: "Material", value: "Mild Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "54",
      code: "DIA50",
      name: "Hex Socket Head Screw (Galvanized)",
      type: "Socket Screws",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Hex socket head screws for concrete",
      material: "Galvanized",
      finish: "Galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822066/galvanized_rwpotv.jpg",
      ],
      specifications: [
        { key: "Type", value: "Socket Screws" },
        { key: "Material", value: "Galvanized" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "55",
      code: "DIA50",
      name: "Hex Socket Countersunk Screw (Stainless Steel)",
      type: "Socket Screws",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Hex socket countersunk screws for concrete",
      material: "Stainless Steel",
      finish: "stainless steel",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822066/stainless_steel_ulgvku.webp",
      ],
      specifications: [
        { key: "Type", value: "Socket Screws" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "56",
      code: "DIA50",
      name: "Set Screw (Stainless Steel)",
      type: "Socket Screws",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Set screws for concrete",
      material: "Stainless Steel",
      finish: "stainless steel",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822067/stainless_steel_vvisf2.jpg",
      ],
      specifications: [
        { key: "Type", value: "Socket Screws" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "57",
      code: "DIA50",
      name: "Socket Button Screw (Mild Steel)",
      type: "Socket Screws",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Socket button screws for concrete",
      material: "Mild Steel",
      finish: "mild steel",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822068/socket_button_screw-mild_steel_vlvobl.webp",
      ],
      specifications: [
        { key: "Type", value: "Socket Screws" },
        { key: "Material", value: "Mild Steel" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    {
      id: "58",
      code: "DIA50",
      name: "Socket Button Flange Screw (Galvanized)",
      type: "Socket Screws",
      price: 2.5,
      vatPrice: 3.0,
      stock: 70,
      description: "Socket button flange screws for concrete",
      material: "Galvanized",
      finish: "galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754822067/socket-button_flange-screwg_galvanized_onoztv.jpg",
      ],
      specifications: [
        { key: "Type", value: "Socket Screws" },
        { key: "Material", value: "Galvanized" },
        { key: "Diameter", value: "50mm" },
        { key: "Embedment Depth", value: "160mm" },
      ],
    },
    // WASHERS
    {
      id: "59",
      code: "WASHER50",
      name: "Flat Washer (Galvanized)",
      type: "Washers",
      price: 0.1,
      vatPrice: 0.12,
      stock: 100,
      description: "Flat washers for concrete",
      material: "Galvanized",
      finish: "galvanized",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754825737/flat_washer_fpkihq.jpg",
      ],
      specifications: [
        { key: "Type", value: "Washers" },
        { key: "Material", value: "Galvanized" },
        { key: "Diameter", value: "50mm" },
      ],
    },
    {
      id: "60",
      code: "WASHER50",
      name: "Spring Washer (Stainless Steel)",
      type: "Washers",
      price: 0.15,
      vatPrice: 0.18,
      stock: 100,
      description: "Spring washers for concrete",
      material: "Stainless Steel",
      finish: "stainless steel",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754825748/spring_washer_xjxeru.jpg",
      ],
      specifications: [
        { key: "Type", value: "Washers" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
      ],
    },
    {
      id: "61",
      code: "WASHER50",
      name: "Nylon Rubber Washer (Rubber)",
      type: "Washers",
      price: 0.15,
      vatPrice: 0.18,
      stock: 100,
      description: "Nylon rubber washers for concrete",
      material: "Rubber",
      finish: "rubber",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754825746/rubber-nylon_washer_m9vtv8.jpg",
      ],
      specifications: [
        { key: "Type", value: "Washers" },
        { key: "Material", value: "Rubber" },
        { key: "Diameter", value: "50mm" },
      ],
    },
    {
      id: "62",
      code: "WASHER50",
      name: "Internal Tooth Lock Washer (Stainless Steel)",
      type: "Washers",
      price: 0.15,
      vatPrice: 0.18,
      stock: 100,
      description: "Internal tooth lock washers for concrete",
      material: "Stainless Steel",
      finish: "stainless steel",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754825740/internal_tooth_lock_washer_soguh3.jpg",
      ],
      specifications: [
        { key: "Type", value: "Washers" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
      ],
    },
    {
      id: "63",
      code: "WASHER50",
      name: "External Tooth Lock Washer (Stainless Steel)",
      type: "Washers",
      price: 0.15,
      vatPrice: 0.18,
      stock: 100,
      description: "External tooth lock washers for concrete",
      material: "Stainless Steel",
      finish: "stainless steel",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754825735/external_tooth_lock_washer_xauzkd.jpg",
      ],
      specifications: [
        { key: "Type", value: "Washers" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
      ],
    },
    {
      id: "64",
      code: "WASHER50",
      name: "Crescent Washer (Stainless Steel)",
      type: "Washers",
      price: 0.15,
      vatPrice: 0.18,
      stock: 100,
      description: "Crescent washers for concrete",
      material: "Stainless Steel",
      finish: "stainless steel",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754825732/crescent_washer_bh08bq.webp",
      ],
      specifications: [
        { key: "Type", value: "Washers" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
      ],
    },
    {
      id: "65",
      code: "WASHER50",
      name: "Conical Washer (Stainless Steel)",
      type: "Washers",
      price: 0.15,
      vatPrice: 0.18,
      stock: 100,
      description: "Conical washers for concrete",
      material: "Stainless Steel",
      finish: "stainless steel",
      size: "50mm",
      images: [
        "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1754825729/conical_washer_mafwbr.jpg",
      ],
      specifications: [
        { key: "Type", value: "Washers" },
        { key: "Material", value: "Stainless Steel" },
        { key: "Diameter", value: "50mm" },
      ],
    },
  ],
  featuredTitle: "Why buy your hardware fasteners from Beakom?",
  featuredSubTitle:
    "Your one-stop shop for quality and reliability, providing you with the best products and services.",
  favicon: "Beakom/beakom-favicon.png",
  companyNo: "",
};
export default clientBeakomConfig;
