import {
  faShieldAlt,
  faStar,
  faClock,
  faPrint,
  faMobileAlt,
  faPalette,
  faRocket,
  faHeart,
} from "@fortawesome/free-solid-svg-icons";

import type { ClientConfig } from "../types/Config";

const clientPrintifyConfig: ClientConfig = {
  name: "Printify Covers",
  logo: "Printify/printify-logo.jpg",
  primaryColor: "#2563eb",
  primaryColorLight: "#3b82f675",
  secondaryColor: "#1e293b",
  tagline: "Custom Phone Covers, Perfectly Printed!",
  fontFamily: "Inter, system-ui, sans-serif",
  currencySymbol: "£",
  isBooking: false,

  // Project template config starts here
  header: {
    title: "Our Custom Creations",
    subtitle: "Explore our portfolio of unique phone cover designs.",
  },
  cta: {
    title: "Ready to create your custom phone cover?",
    subtitle: "Upload your design or get inspired by our collections. Contact us for bulk orders and special requests.",
    buttonText: "Design Now",
    link: "/design", // when the design page is converted should be added here.
  },

  features: [
    {
      icon: faPrint,
      title: "Premium Printing",
      description: "High-resolution printing with vibrant, long-lasting colors.",
    },
    {
      icon: faMobileAlt,
      title: "Perfect Fit",
      description: "Precision-cut covers for all phone models and brands.",
    },
    {
      icon: faPalette,
      title: "Custom Designs",
      description: "Bring your ideas to life with our custom design service.",
    },
    {
      icon: faShieldAlt,
      title: "Durable Protection",
      description: "Scratch-resistant and impact-absorbing materials.",
    },
    {
      icon: faRocket,
      title: "Fast Turnaround",
      description: "Quick production without compromising quality.",
    },
    {
      icon: faStar,
      title: "Quality Guarantee",
      description: "Perfect prints every time or we'll reprint.",
    },
  ],
  about: {
    title: "About Printify",
    subtitle: "Your Partner in Custom Phone Cover Printing",
    description:
      "Printify specializes in creating high-quality, custom-printed phone covers that protect your device while showcasing your unique style.",
    image: "/images/printify-team.jpg",

    // Story section fields
    mainImage: "Printify/printify-workshop.jpg",
    mainImageAlt: "Printify Printing Workshop",
    storyTitle: "Our Printing Journey",
    story1:
      "Founded with a passion for creativity and technology, Printify started as a small workshop dedicated to bringing personalized phone protection to everyone.",
    story2: "We've grown into a leading printing service by combining state-of-the-art printing technology with exceptional customer service.",
    story3:
      "Our mission is to transform ordinary phone cases into extraordinary personal statements while providing reliable protection for your devices.",

    // Values section
    values: [
      {
        icon: faPalette,
        title: "Creativity",
        description: "We empower self-expression through custom designs and unlimited creative possibilities.",
      },
      {
        icon: faPrint,
        title: "Precision",
        description: "Every print is meticulously crafted with attention to detail and color accuracy.",
      },
      {
        icon: faClock,
        title: "Quick Delivery",
        description: "Fast production times to get your custom covers to you when you need them.",
      },
      {
        icon: faHeart,
        title: "Customer Love",
        description: "We're passionate about making our customers happy with every order.",
      },
    ],

    // Founder section fields
    founderImage: "/images/founder.jpg", // or your founder image path
    founderTitle: "Meet The Founder",
    founderName: "Alex Morgan",
    founderRole: "Founder & Creative Director",
    founderBio1:
      "With a background in graphic design and digital printing, Alex Morgan has always been passionate about helping people express their individuality through custom products.",
    founderBio2:
      "In 2018, Alex founded Printify Covers with a vision to combine cutting-edge printing technology with personalized design, creating phone covers that are both protective and expressive.",
    founderBio3: "Alex's commitment to quality and innovation has made Printify Covers the go-to destination for custom phone cover printing.",
    // Optional SEO fields
    // seoTitle: "About Printify Covers - Custom Phone Cover Printing",
    // seoDescription: "Learn about Printify Covers, your trusted partner for high-quality custom phone cover printing with vibrant designs and perfect fit.",
    // seoKeywords: "about Printify Covers, custom phone covers, printing service, personalized cases",
    // seoUrl: "https://yourdomain.com/about"
  },
  phoneOffice: "053 987 6543",
  phoneMobile: "(+233) 53 987 6543",
  email: "hello@printifycovers.com",
  address: "Digital Plaza, Tech Avenue, Accra",
  openHours1: "Monday - Friday: 9:00 AM - 6:00 PM",
  openHours2: "Saturday: 10:00 AM - 4:00 PM",
  openHours3: "Sunday: Closed",
  location:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2478.8832781725673!2d-0.22423112337504625!3d51.58870257183188!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487610cf8629b6f3%3A0x4802d5cd36a9a63!2s137%20Brent%20St%2C%20London%20NW4%204DJ!5e0!3m2!1sen!2suk!4v1747849113481!5m2!1sen!2suk",
  hero: {
    title: "Express Yourself with Custom Phone Covers",
    subtitle: "High-quality printing for unique designs that protect your device in style.",

    backgroundImage: "Printify/printify-background.jpg",
  },
  featuredItems: {
    title: "Popular Designs",
    subtitle: "Best-selling phone covers loved by our customers",
    products: [
      {
        id: 1,
        name: "Designer Pattern Case",
        image: "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761248947/zebra_close_up_wep3fe.jpg",
        images: [
          "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761248947/zebra_close_up_wep3fe.jpg",
          "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761248947/zebra_normal_xnayhj.jpg",
          "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761396305/leoppard_case_lnxhwv.webp",
          "https://res.cloudinary.com/dxwqt6yrg/video/upload/v1761396448/rotating_case_pyra6u.mp4",
        ],
        price: 49.99,
        originalPrice: 64.99,
        stock: 23,
        priceRange: {
          min: 39.99,
          max: 79.99,
        },
        rating: 4.7,
      },
      {
        id: 2,
        name: "Pink Finish Cover",
        image: "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761249192/pink_cover_hbwrn4.jpg",
        price: 39.99,
        originalPrice: 49.99,
        stock: 15,
        priceRange: {
          min: 29.99,
          max: 65.99,
        },
        rating: 4.5,
      },
      {
        id: 3,
        name: "Black Photo Case",
        image: "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761249121/black_cover_ciduok.jpg",
        price: 55.99,
        originalPrice: 69.99,
        stock: 8,
        priceRange: {
          min: 45.99,
          max: 89.99,
        },
        rating: 4.9,
      },
      {
        id: 4,
        name: "Clear Transparent Cover",
        image: "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761249085/transpaent_lapjjm.jpg",
        price: 32.99,
        originalPrice: 42.99,
        stock: 0, // Out of stock
        priceRange: {
          min: 24.99,
          max: 54.99,
        },
        rating: 4.3,
      },
      {
        id: 5,
        name: "Glossy Premium Case",
        image: "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761249192/green_cover_fusk8g.jpg",
        images: [
          "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761249192/green_cover_fusk8g.jpg",
          "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761249192/pink_cover_hbwrn4.jpg",
          "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761249121/black_cover_ciduok.jpg",
          "https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761248947/zebra_close_up_wep3fe.jpg",
        ],
        price: 45.99,
        originalPrice: 59.99,
        stock: 42,
        priceRange: {
          min: 35.99,
          max: 75.99,
        },
        rating: 4.8,
      },
    ],
  },
  filterGroup: [
    {
      title: "Phone Cover Type",
      options: [
        { name: "Hard Cases", count: 113, selected: false },
        { name: "Soft TPU Cases", count: 140, selected: false },
        { name: "Clear Cases", count: 348, selected: false },
        { name: "Wallet Cases", count: 150, selected: false },
        { name: "Bumper Cases", count: 200, selected: false },
        { name: "MagSafe Compatible", count: 100, selected: false },
        { name: "Designer Series", count: 50, selected: false },
        { name: "Photo Cases", count: 75, selected: false },
        { name: "Custom Text Cases", count: 30, selected: false },
        { name: "Limited Edition", count: 30, selected: false },
      ],
      type: "checkbox",
    },
    {
      title: "Material",
      options: [
        { name: "Polycarbonate", count: 140, selected: false },
        { name: "TPU", count: 113, selected: false },
        { name: "Silicone", count: 80, selected: false },
        { name: "Leather", count: 50, selected: false },
        { name: "Metal", count: 30, selected: false },
        { name: "Wood", count: 25, selected: false },
        { name: "Glass", count: 13, selected: false },
        { name: "Hybrid", count: 348, selected: false },
      ],
      type: "checkbox",
    },
    {
      title: "Finish",
      options: [
        { name: "Glossy", count: 780, selected: false },
        { name: "Matte", count: 466, selected: false },
        { name: "Transparent", count: 300, selected: false },
        { name: "Metallic", count: 200, selected: false },
        { name: "Textured", count: 150, selected: false },
        { name: "Glitter", count: 100, selected: false },
      ],
      type: "checkbox",
    },
  ],
  products: [
    // HARD CASES
    {
      id: "1",
      code: "HCIP14",
      name: "Hard Case for iPhone 14 (Glossy Finish)",
      type: "Hard Cases",
      price: 45.99,
      vatPrice: 55.19,
      stock: 100,
      description: "Premium glossy hard case with crystal clear print quality",
      material: "Polycarbonate",
      finish: "Glossy",
      size: "iPhone 14",
      images: ["https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761252531/custom_design_xuey5r.jpg"],
      specifications: [
        { key: "Type", value: "Hard Case" },
        { key: "Material", value: "Polycarbonate" },
        { key: "Compatibility", value: "iPhone 14" },
        { key: "Finish", value: "Glossy" },
      ],
    },
    {
      id: "2",
      code: "MCS23",
      name: "Matte Case for Samsung S23",
      type: "Hard Cases",
      price: 39.99,
      vatPrice: 47.99,
      stock: 250,
      description: "Sleek matte finish case with anti-fingerprint coating",
      material: "Polycarbonate",
      finish: "Matte",
      size: "Samsung S23",
      images: ["https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761252630/good_friend_kdfnik.jpg"],
      specifications: [
        { key: "Type", value: "Hard Case" },
        { key: "Material", value: "Polycarbonate" },
        { key: "Compatibility", value: "Samsung S23" },
        { key: "Finish", value: "Matte" },
      ],
    },
    {
      id: "3",
      code: "TCP13",
      name: "Transparent Clear Case for iPhone 13",
      type: "Clear Cases",
      price: 35.99,
      vatPrice: 43.19,
      stock: 80,
      description: "Crystal clear case that shows off your phone's original color",
      material: "TPU",
      finish: "Transparent",
      size: "iPhone 13",
      images: ["https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761249192/green_cover_fusk8g.jpg"],
      specifications: [
        { key: "Type", value: "Clear Case" },
        { key: "Material", value: "TPU" },
        { key: "Compatibility", value: "iPhone 13" },
        { key: "Finish", value: "Transparent" },
      ],
    },
    {
      id: "4",
      code: "WLP14",
      name: "Wallet Case with Card Slots",
      type: "Wallet Cases",
      price: 59.99,
      vatPrice: 71.99,
      stock: 500,
      description: "Premium leather wallet case with multiple card slots",
      material: "Leather",
      finish: "Textured",
      size: "iPhone 14",
      images: ["https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761249192/pink_cover_hbwrn4.jpg"],
      specifications: [
        { key: "Type", value: "Wallet Case" },
        { key: "Material", value: "Leather" },
        { key: "Card Slots", value: "3" },
        { key: "Cover", value: "Magnetic" },
      ],
    },
    {
      id: "5",
      code: "BMP13",
      name: "Bumper Case with Metallic Finish",
      type: "Bumper Cases",
      price: 49.99,
      vatPrice: 59.99,
      stock: 1000,
      description: "Protective bumper case with metallic accents",
      material: "Hybrid",
      finish: "Metallic",
      size: "iPhone 13",
      images: ["https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761249121/black_cover_ciduok.jpg"],
      specifications: [
        { key: "Type", value: "Bumper Case" },
        { key: "Material", value: "Hybrid" },
        { key: "Compatibility", value: "iPhone 13" },
        { key: "Finish", value: "Metallic" },
      ],
    },
    {
      id: "6",
      code: "MSG14",
      name: "MagSafe Compatible Case",
      type: "MagSafe Compatible",
      price: 65.99,
      vatPrice: 79.19,
      stock: 150,
      description: "Wireless charging compatible case with strong magnets",
      material: "Polycarbonate",
      finish: "Matte",
      size: "iPhone 14",
      images: ["https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761249192/green_cover_fusk8g.jpg"],
      specifications: [
        { key: "Type", value: "MagSafe Case" },
        { key: "Material", value: "Polycarbonate" },
        { key: "Wireless Charging", value: "Yes" },
        { key: "Magnet Strength", value: "Strong" },
      ],
    },
    {
      id: "7",
      code: "DSP15",
      name: "Designer Series Pattern Case",
      type: "Designer Series",
      price: 55.99,
      vatPrice: 67.19,
      stock: 75,
      description: "Exclusive designer pattern with premium print quality",
      material: "TPU",
      finish: "Textured",
      size: "iPhone 15",
      images: ["https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761248947/zebra_close_up_wep3fe.jpg"],
      specifications: [
        { key: "Type", value: "Designer Case" },
        { key: "Material", value: "TPU" },
        { key: "Compatibility", value: "iPhone 15" },
        { key: "Collection", value: "Designer Series" },
      ],
    },
    {
      id: "8",
      code: "PCP14",
      name: "Custom Photo Case",
      type: "Photo Cases",
      price: 52.99,
      vatPrice: 63.59,
      stock: 800,
      description: "High-resolution photo print on premium case material",
      material: "Polycarbonate",
      finish: "Glossy",
      size: "iPhone 14",
      images: ["https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761249192/pink_cover_hbwrn4.jpg"],
      specifications: [
        { key: "Type", value: "Photo Case" },
        { key: "Material", value: "Polycarbonate" },
        { key: "Print Quality", value: "High-Resolution" },
        { key: "Customization", value: "Full Wrap" },
      ],
    },
    {
      id: "9",
      code: "TXC13",
      name: "Custom Text Case",
      type: "Custom Text Cases",
      price: 42.99,
      vatPrice: 51.59,
      stock: 60,
      description: "Personalized text case with your choice of font and color",
      material: "TPU",
      finish: "Matte",
      size: "iPhone 13",
      images: ["https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761248947/zebra_normal_xnayhj.jpg"],
      specifications: [
        { key: "Type", value: "Text Case" },
        { key: "Material", value: "TPU" },
        { key: "Customization", value: "Text Only" },
        { key: "Font Options", value: "Multiple" },
      ],
    },
    {
      id: "10",
      code: "LES15",
      name: "Limited Edition Series",
      type: "Limited Edition",
      price: 79.99,
      vatPrice: 95.99,
      stock: 300,
      description: "Exclusive limited edition design with numbered series",
      material: "Hybrid",
      finish: "Metallic",
      size: "iPhone 15",
      images: ["https://res.cloudinary.com/dxwqt6yrg/image/upload/v1761249192/green_cover_fusk8g.jpg"],
      specifications: [
        { key: "Type", value: "Limited Edition" },
        { key: "Material", value: "Hybrid" },
        { key: "Edition", value: "Numbered Series" },
        { key: "Availability", value: "Limited" },
      ],
    },
  ],
  featuredTitle: "Why choose Printify Covers for your custom phone cases?",
  featuredSubTitle: "Your premier destination for high-quality printing and unique designs that protect your device in style.",
  favicon: "Printify/printify-favicon.png",
  companyNo: "98765432",
};
export default clientPrintifyConfig;
